server.port=8081
spring.application.name=descuento-service

# Base de datos PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/descuentos_db
spring.datasource.username=bootcamp_user
spring.datasource.password=bootcamp_password_sec2026
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always